import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;

public class Setup {
    public JPanel panel1;
    public JButton connectButton;
    public JComboBox scopeNicknameComboBox;
    public JCheckBox a10xResistanceProbeCheckBox;
    public JCheckBox builtInDisplayCheckBox;
    public JCheckBox wirelessCardCheckBox;
    public JCheckBox functionGeneratorCheckBox;
    public JTextField textField1;
    public JPanel panel2;
    public JComboBox comboBox1;
    public JComboBox comboBox2;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        panel1.add(panel3, BorderLayout.NORTH);
        panel3.setBorder(BorderFactory.createTitledBorder("Device Setup"));
        final JLabel label1 = new JLabel();
        label1.setText("Model");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        panel3.add(label1, gbc);
        scopeNicknameComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("QScope X");
        defaultComboBoxModel1.addElement("QScope (R2)");
        defaultComboBoxModel1.addElement("DScope (R2)");
        scopeNicknameComboBox.setModel(defaultComboBoxModel1);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        panel3.add(scopeNicknameComboBox, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Accessories");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel3.add(label2, gbc);
        a10xResistanceProbeCheckBox = new JCheckBox();
        a10xResistanceProbeCheckBox.setText("10x Resistance Probe");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridwidth = 3;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel3.add(a10xResistanceProbeCheckBox, gbc);
        builtInDisplayCheckBox = new JCheckBox();
        builtInDisplayCheckBox.setText("Built-in Display");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.gridwidth = 3;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel3.add(builtInDisplayCheckBox, gbc);
        wirelessCardCheckBox = new JCheckBox();
        wirelessCardCheckBox.setText("Wireless Card");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.gridwidth = 3;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel3.add(wirelessCardCheckBox, gbc);
        functionGeneratorCheckBox = new JCheckBox();
        functionGeneratorCheckBox.setText("Function Generator");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.gridwidth = 3;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel3.add(functionGeneratorCheckBox, gbc);
        textField1 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(textField1, gbc);
        final JLabel label3 = new JLabel();
        label3.setHorizontalAlignment(10);
        label3.setHorizontalTextPosition(0);
        label3.setText("Nickname");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        panel3.add(label3, gbc);
        connectButton = new JButton();
        connectButton.setText("Connect");
        panel1.add(connectButton, BorderLayout.SOUTH);
        panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.add(panel2, BorderLayout.CENTER);
        panel2.setBorder(BorderFactory.createTitledBorder("Communication Setup"));
        final JLabel label4 = new JLabel();
        label4.setText("Serial Port");
        panel2.add(label4);
        comboBox1 = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel2 = new DefaultComboBoxModel();
        defaultComboBoxModel2.addElement("COM1");
        defaultComboBoxModel2.addElement("COM2");
        defaultComboBoxModel2.addElement("COM3");
        defaultComboBoxModel2.addElement("COM4");
        defaultComboBoxModel2.addElement("COM5");
        comboBox1.setModel(defaultComboBoxModel2);
        panel2.add(comboBox1);
        final JLabel label5 = new JLabel();
        label5.setText("Baud Rate");
        panel2.add(label5);
        comboBox2 = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel3 = new DefaultComboBoxModel();
        defaultComboBoxModel3.addElement("9600");
        defaultComboBoxModel3.addElement("115200");
        defaultComboBoxModel3.addElement("250000");
        comboBox2.setModel(defaultComboBoxModel3);
        panel2.add(comboBox2);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }
}
